config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope '(:locale)' do
    namespace :manage do
      root to: 'manage#start', as: :manage
      resources :pages
      resources :page_parts
      resources :products
      resources :reports do
        member do
          get :city_reports
        end
      end
      resources :marathons do
        member do
          get :participants
          get :participants_csv
        end
      end
    end

    devise_for :users

    resources :pages, only: [:show]
    resources :participants, only: [:create] do
      member do
        get :confirm
      end
    end
    resources :reports, only: [:show]

    get '/thank-you', to: 'home#thanks', as: :thanks
    get '/v2', to: 'home#v2', as: :v2

    root 'home#index'
  end
end

app/views/shared/_admin_header.html.haml
%nav.navbar.navbar-inverse{:role => "navigation"}
  .container

    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-9", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} SoftServe Donate

    #bs-example-navbar-collapse-9.collapse.navbar-collapse.pull-right
      %ul.nav.navbar-nav
        = content_tag :li, class: "#{'active' if admin_menu?(:content)}" do
          = link_to "Content", manage_page_parts_path

        = content_tag :li, class: "#{'active' if admin_menu?(:pages)}" do
          = link_to "Pages", manage_pages_path

        = content_tag :li, class: "#{'active' if admin_menu?(:products)}" do
          = link_to "Products", manage_products_path

        = content_tag :li, class: "#{'active' if admin_menu?(:marathons)}" do
          = link_to "Marathons", manage_marathons_path
        = content_tag :li, class: "#{'active' if admin_menu?(:reports)}" do
          = link_to "Reports", manage_reports_path
        %li
          = link_to destroy_user_session_path, :method => :delete do
            %spancontent_tag.glyphicon.glyphicon-off
            ="Sign out (#{current_user.email})"

    .clearfix

app/views/shared/_background_video_player.html.haml
%a{href: '#', class: "player #{local_assigns[:class]}", style: "#{local_assigns[:styles]}", data: { property: properties.to_json.html_safe }}
%div{id: properties[:containment].gsub(/^#/, ''), style: 'display: block; background: rgba(0,0,0,0.1); position: absolute; height: 100%; width: 100%'}

app/views/shared/_footer.html.haml
%footer.container.footer#footer
  .footer_links
    .pull-left
    .pull-right
      = link_to 'Панель керування', manage_manage_path
    .clearfix

app/views/shared/_header.html.haml
.header-cont
  %nav.navbar.navbar-static-top{:role => "navigation"}
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-8", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a{href: root_path}
        %span.logo
        %span.logo_text Заради життя

    .soc
      - if current_site.fb
        %a{href: "#{current_site.fb}"}
          %i.fa.fa-facebook
      - if current_site.gp
        %a{href: "#{current_site.gp}"}
          %i.fa.fa-google-plus
      - if current_site.tw
        %a{href: "#{current_site.tw}"}
          %i.fa.fa-twitter
      - if current_site.vk
        %a{href: "#{current_site.vk}"}
          %i.fa.fa-vk

    .language.hide
      %a{href: '/uk'}
        %span.flag.flag-ua
      %a{href: '/en'}
        %span.flag.flag-england

    #bs-example-navbar-collapse-8.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Проекти', [:projects]
        %li
          = link_to 'Події', [:events]
        %li
          %a{href: '/#who_we_are'} 
            = page_part 'who_we_are_link'
        %li
          %a{href: '/#instruction'} 
            = page_part 'instruction_link'
        %li
          = link_to page_part('contact_link'), new_contact_path

        - Page.root_pages.except_about.for_header.each do |page|
          %li
            = link_to page do
              = page.seo_title

app/views/shared/_locale_switch.html.haml
.row
  .col-lg-10.col-md-10.text-right.language
    = link_to 'УКР', root_path(locale: :uk), class: "locale-switch #{'active' if active_locale?(:uk)}"
    = link_to 'ENG', root_path(locale: :en), class: "locale-switch #{'active' if active_locale?(:en)}"

app/views/shared/_slider.html.haml
.slider-section{class: "#{'green-slider' unless marathon.try(:voting?) }"}
  %h2= t :slider_header
  .container-fluid
    .row
      .col-xs-7.col-xs-offset-1
        .slick-slider.slider-reports
          - reports.without_bucket.each do |report|
            %div.slider-item
              %h3.thumb-header=raw report.name
              %span.period
                - if report.report_month.present?
                  =l report.report_month.to_date, format: :month
                  =l report.report_month.to_date, format: :year
                  - if report.bucket? && report.end_month.present?
                    &#8212;
                    =l report.end_month.to_date, format: :month
                    =l report.end_month.to_date, format: :year
              %hr
              %p.description=raw report.description
              = link_to t(:show_report), report, class: 'btn btn-primary'

      .col-xs-3.bucket-section
        .slick-slider.bucket-slider
          - Report.with_bucket.ordered.each do |report|
            %div.slider-item
              %h3.thumb-header=raw report.name
              %span.period
                - if report.report_month.present?
                  =l report.report_month.to_date, format: :month
                  =l report.report_month.to_date, format: :year
                  - if report.bucket? && report.end_month.present?
                    &#8212;
                    =l report.end_month.to_date, format: :month
                    =l report.end_month.to_date, format: :year
              %hr
              %p.description=raw report.description
              = link_to t(:show_report), report, class: 'btn btn-primary'
      .clearfix