config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope '(:locale)' do
    namespace :manage do
      root to: 'manage#start', as: :manage
      resources :pages
      resources :page_parts
      resources :products
      resources :reports do
        member do
          get :city_reports
        end
      end
      resources :marathons do
        member do
          get :participants
          get :participants_csv
        end
      end
    end

    devise_for :users

    resources :pages, only: [:show]
    resources :participants, only: [:create] do
      member do
        get :confirm
      end
    end
    resources :reports, only: [:show]

    get '/thank-you', to: 'home#thanks', as: :thanks
    get '/v2', to: 'home#v2', as: :v2

    root 'home#index'
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id              :integer          not null, primary key
#  organization_id :integer
#  name            :string(255)
#  description     :text
#  image           :string(255)
#  amount          :integer
#  completed       :boolean          default(FALSE)
#  category_id     :integer
#  created_at      :datetime
#  updated_at      :datetime
#  preview         :string(255)
#  featured        :boolean          default(FALSE)
#

class Project < ActiveRecord::Base

  mount_uploader :preview, PhotoUploader

  scope :completed, -> {where(:completed => true)}
  scope :open,      -> {where(:completed => false)}
  scope :featured,  -> {where(:featured  => true)}
  scope :random,    -> {order("rand()")}
  scope :by_completed, -> {order(:completed)}

  belongs_to :organization
  belongs_to :category

  has_many :credits, dependent: :destroy
  has_many :usages,  dependent: :destroy
  has_many :photos,  as: :photable, dependent: :destroy
  has_many :documents, as: :documentable, dependent: :destroy

  accepts_nested_attributes_for :photos,    allow_destroy: true, reject_if: proc { |attributes| attributes['photo'].blank? }
  accepts_nested_attributes_for :documents, allow_destroy: true, reject_if: proc { |attributes| attributes['document'].blank? }

  validates :name, :organization, :amount, :description, presence: true

  def self.received
    all.map(&:total_received).sum
  end

  def self.spent
    all.map(&:total_spent).sum
  end

  def self.need
    open.all.map(&:amount).sum - open.received
  end

  def to_param
    "#{self.id}-#{self.name}".mb_chars.downcase.gsub(/[^a-z0-9а-яії]+/i, '-').transliterate
  end

  def total_received
    self.credits.map(&:amount).sum
  end

  def total_spent
    self.usages.map(&:amount).sum
  end

  def available
    a = total_received - total_spent
    a > 0 ? a : 0
  end

  def percent_complete
    (self.total_received * 100) / amount rescue 0
  end

  def ui_percent_complete
    [self.percent_complete, 100].min rescue 0
  end

  def short_description
    Nokogiri::HTML(self.description).text.truncate(270, ommision: "...")
  end

  def order_id
    "project##{self.id}##{Time.now.to_i}"
  end

  def active?
    !self.completed
  end

  def money_collected?
    total_received >= amount
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.by_completed
  end

  def new_payment
    @project = Project.find(params[:id])
    @liqpay_request = Liqpay::Request.new(
      amount:      params[:amount].presence || "20",
      currency:    'UAH',
      type:        'donate',
      order_id:    @project.order_id,
      description: params[:name].presence || 'анонім',
      result_url:  project_url(@project),
      server_url:  liqpay_payment_project_url(@project)
    )
    respond_to do |page|
      page.js {}
    end
  end

  def show
    @project = Project.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_gallery.html.haml
#blueimp-gallery.blueimp-gallery
  / The container for the modal slides
  .slides
  / Controls for the borderless lightbox
  %h3.title
  %a.prev ‹
  %a.next ›
  %a.close ×
  %a.play-pause
  %ol.indicator
  / The modal dialog, which will be used to wrap the lightbox content
  .modal.fade
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", :type => "button"} ×
          %h4.modal-title
        .modal-body.next
        .modal-footer
          %button.btn.btn-default.pull-left.prev{:type => "button"}
            %i.glyphicon.glyphicon-chevron-left
            Попередня
          %button.btn.btn-primary.next{:type => "button"}
            Наступна
            %i.glyphicon.glyphicon-chevron-right

app/views/projects/_new_payment.html.haml
= liqpay_button @liqpay_request, title: 'Переказати гроші'.html_safe

app/views/projects/_project.html.haml
.col-sm-6.col-md-4
  .thumbnail.project
    = link_to project do
      = image_tag project.preview? ? project.preview_url(:thumb_wide) : 'default_project.jpg', class: 'project-img'
    .organization
      - if project.organization
        %b
          = project.organization.name.capitalize
        = image_tag project.organization.logo_url (:thumb_mini)
    .caption
      - if project.completed
        = image_tag 'completed.png', class: 'completed'
      - elsif project.money_collected?
        = image_tag 'money_collected.png', class: 'completed'
      %h3.truncate
        = link_to truncate(project.name, length: 30), project, title: project.name
      .description
        = link_to project do
          %p
            = project.short_description
      .progress
        .progress-bar.progress-bar-striped.progress-bar-success.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => project.percent_complete, :role => "progressbar", :style => "width: #{project.ui_percent_complete}%"}
          = "#{project.percent_complete}% зібрано"
      .amount
        - if project.active?
          .pull-left
            %strong= number_to_currency project.amount, precision: 0
            треба
        .pull-right
          %strong= number_to_currency project.total_received, precision: 0
          зібрано
        .clearfix

app/views/projects/index.html.haml
= title "Проекти"

.projects-cont.container
  %h2
    = page_part "projects_title"
  .row
    = render @projects

app/views/projects/new_payment.js.erb
$("#payment").html("<%= escape_javascript(render('new_payment')) %>");
$("#payment form").submit();

app/views/projects/participants.html.haml
.row
  .col-md-6
    %h1.left Participants

.clearfix
.pull-right
  = link_to 'Export to CSV', participants_csv_manage_marathon_path(@marathon, format: :csv), class: 'btn btn-sm btn-success'

- if @participants.any?
  .pull-left
    = paginate @participants, window: 3

  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Email
        %th Amount

    %tbody
      - @participants.each do |participant|
        %tr
          %td= participant.name
          %td= participant.email
          %td= participant.amount
  .pull-right
    = paginate @participants, window: 3
  %br

- else
  %p No Participants.

app/views/projects/show.html.haml
= title @project.name

= page_meta({ title: @project.name,
              description: @project.short_description.gsub(/["']/,''),
              url: request.original_url,
              image: full_image_url(@project.preview_url) })

.page-container
  .container
    .row.project-page
      .col-md-12
        %ul.nav.nav-tabs.project-nav-tabs{role: "tablist"}
          %li.active
            %a{href: "#general", role: "tab", data: {toggle: "tab"}}
              Проект
          %li
            %a{href: "#photos", role: "tab", data: {toggle: "tab"}}
              Фотографії
              %span.label.label-default= @project.photos.count
          %li
            %a{href: "#documents", role: "tab", data: {toggle: "tab"}}
              Документи
              %span.label.label-default= @project.documents.count
          %li
            %a{href: "#actions", role: "tab", data: {toggle: "tab"}}
              Отримані та витрачені кошти
      .col-md-12
        .row.project-content
          .col-md-9
            .project-show
              .tab-content
                .tab-pane.fade.in.active#general
                  - if @project.preview?
                    = image_tag @project.preview.url(:thumb_preview), class: 'thumbnail pull-left obj_thumbnail'
                  %h1= @project.name
                  = raw @project.description
                  .clearfix
                .tab-pane.fade.in#photos
                  %h2
                    Фото
                    .btn-group{"data-toggle" => "buttons"}
                      %label.btn.btn-success.btn-xs
                        %i.glyphicon.glyphicon-leaf
                        %input#borderless-checkbox{:type => "checkbox"}/
                        Без країв
                  - if @project.photos.any?
                    #links
                      - @project.photos.each_with_index do |photo, index|
                        = link_to photo.photo_url(:thumb_xwide), title: @project.name, data: {gallery: ""} do
                          = image_tag photo.photo_url(:thumb)

                  - else
                    %p Розділ пустий.

                .tab-pane.fade.in#documents
                  %h2 Документи
                  - if @project.documents.any?
                    %ul
                      - @project.documents.each do |e|
                        %li= link_to e.ui_file_name, e.document.url
                  - else
                    %p Розділ пустий.

                .tab-pane.fade.in#actions
                  %h2 Отримані та витрачені кошти
                  .row
                    .col-md-6
                      - if @project.credits.any?
                        %strong Отримані кошти
                        %table.table.table-bordered
                          - @project.credits.sort_by(&:credit_date).each do |e|
                            %tr
                              %td= l e.credit_date, format: :short
                              %td
                                - if e.currency == 'UAH'
                                  = number_to_currency e.amount
                                - else
                                  #{e.original_amount} #{e.currency}
                                  - unless e.original_amount == e.amount
                                    (#{e.amount} UAH)
                              %td= e.from_user
                    .col-md-6
                      - if @project.usages.any?
                        %strong Витрачені кошти
                        %table.table.table-bordered
                          - @project.usages.sort_by(&:usage_date).each do |e|
                            %tr
                              %td= l e.usage_date, format: :short
                              %td
                                - if e.currency == 'UAH'
                                  = number_to_currency e.amount
                                - else
                                  #{e.original_amount} #{e.currency}
                                  - unless e.original_amount == e.amount
                                    (#{e.amount} UAH)
                              %td= e.description.presence || '-'
                    .clearfix

          .col-md-3
            - if permitted?(@project)
              %p.btn-group.btn-group-justified= link_to 'Редагувати', [:edit, :manage, @project], class: 'btn btn-default'
            .caption
              %h3= @project.name
              .description
                .progress
                  .progress-bar.progress-bar-striped.progress-bar-success.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => @project.percent_complete, :role => "progressbar", :style => "width: #{@project.ui_percent_complete}%"}
                    = "#{@project.percent_complete}% зібрано"
                .project-money
                  - if @project.active?
                    %strong= number_to_currency @project.amount
                    %span потрібно зібрати
                    %strong= number_to_currency @project.total_received
                    %span вже зібрано
                  - else
                    %strong= number_to_currency @project.total_received
                    %span зібрано

                - if @project.active?
                  .project-action.btn-group.btn-group-justified.bot-offset-20.well
                    = form_tag [:new_payment, @project], remote: true do
                      .field
                        %label.label.label-danger
                          * Ім'я
                        = text_field_tag :name, '', placeholder: "ваше ім'я або анонімно", class: 'form-control'
                      .field
                        %label.label.label-danger
                          * Сума
                        = text_field_tag :amount, '', placeholder: 'сума допомоги, грн', class: 'form-control'
                      = submit_tag "Підтримати", class: 'btn btn-success'

                - else
                  .well.completed
                    %label.label-danger
                      Проект завершено

            = social_share_button_tag(@project.name, popup: "true", desc: @project.short_description.gsub(/["']/,''), url: request.original_url, image: full_image_url(@project.preview_url))
            .organization
              - if @project.organization
                - if @project.organization.logo.present?
                  .logo= image_tag @project.organization.logo_url (:thumb_small)
                .desc
                  %i проект від
                  %b= @project.organization.name.capitalize
          .clearfix


.clearfix


#payment.hide
= render 'gallery'